### ISSUE TITLE
[CSS] Select options are closed on hover when used in a popin in Firefox 37

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#1145]
# Current behaviour

On Firefox 37, Select options are closed on a mouse hover when used in a Popin.

I use 100% pure focus css.

The list is working when : 
 - I disable the "transform" attribute in the slideInRight KeyFrame animation.
 - I disable the overflow-y

With newer version of Firefox the select options are working.

Web Resources found with the same prob :
https://css-tricks.com/forums/topic/options-disappearing-on-hover-in-firefox/
http://stackoverflow.com/questions/13163613/select-tag-doesnt-work-properly-when-container-has-css3-transform-in-firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=664707

Firefox 37 Win32 Install  : https://ftp.mozilla.org/pub/firefox/releases/37.0/win32/fr/Firefox%20Setup%2037.0.exe

# Expected behaviour

Fix the focus-components CSS or add a hack to firefox 37 to disable the animation:
Here is the fix to disable animation using CSS hack :
```css
/* Disable opening animation for Firefox 37 Only  */
@supports (-moz-appearance:none) and (display:contents)
   and (not (ruby-position:over)) {

   [data-animation].slideInRight {
        animation-name: none;
   }
}
```

Or \<html\>’s conditional classes (http://www.paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/)

Or modernizer ...

## Versions

Focus-core: 0.13.0
Focus-components: 0.13.0

**Comment by pierr** [comment]
@durandx Thanks for your issue.
We have a few browser specific issue.
It will not be in the 0.15 release but in the next.
Thanks

**Comment by Tommass** [comment]
@durandx Can you provide us a screen capture (if possible gif animated) so we can visualize the problem ?

**Comment by durandx** [comment]
Here is the fix to disable animation using CSS hack :
```css
/* Disable opening animation for Firefox 37 Only  */
@supports (-moz-appearance:none) and (display:contents)
   and (not (ruby-position:over)) {

   [data-animation].slideInRight {
        animation-name: none;
   }
}
```
