### ISSUE TITLE
[SnackBar] By default the snackbar is poped behind the popin

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#1182]
# Current behaviour
The snack bar appears behind the popin with the default focus css. In case of an error thrown, in the popin, the error is partially hidden.

# Expected behaviour
The snackbar should be in front of all possible layers (popin included) by default with the css provided by focus.

```css
/* Fix z-index snack-bar*/
[data-focus="snackbar-message-center"] {
    z-index: 1002;
} 
```

## Versions

Focus-core: 0.15.5-beta1[UNOFFICIAL]
Focus-components: 0.15.0
