### ISSUE TITLE
[Label] A way to override requiredChar prop when using a form mixin

### ISSUE THREAD

**Issue by ursuandrei42** [KleeGroup/focus-components#200]
I need to pass the a custom requiredChar to the label component when I'm using a form mixin.

In field/mixin/built-in-components.js the method label() doesn't pass the prop 'requiredChar' to Label component

```javascript
 label() {
        if (this.props.FieldComponent || this.props.InputLabelComponent) {
            return undefined;
        }
        if (this.props.hasLabel) {
            //In the labelCasen there is no reason to pass all props.
            let labelClassName = this._getLabelGridClassName();
            let {isEdit, isRequired, name} = this.props;
            return (
                <Label
                    isEdit={isEdit}
                    isRequired={isRequired}
                    key={name}
                    name={name}
                    style={{className: labelClassName}}
                />
            );
        }
    },
```

**Comment by pierr** [comment]
This should be done via CSS.
The field has an attribute `[data-required]` and  with a css `::after` add the symbol you want.

**Comment by pierr** [comment]
https://github.com/KleeGroup/focus-components/blob/master/src/common/label/index.js#L16

**Comment by pierr** [comment]
The requiredChar will be removed in the next release

**Comment by pierr** [comment]
![image](https://cloud.githubusercontent.com/assets/286966/9362453/b7e62a82-46a0-11e5-9b16-98d89e8e9e2f.png)

**Comment by durandx** [comment]
Pierr that's what we've done, but the '*' is still hardcoded and concatened after the label

**Comment by pierr** [comment]
Yes @Tommass  is on it, that's why the issue is still open.
Il will be in the next version.

**Comment by Tommass** [comment]
To override the *, please now override this css.

```css
[data-focus="field"] {
    &[data-mode="edit"] {
        &[data-required="true"] {
            label {
                &:after {
                    content: "*";
                    margin-left: 3px;
                }
            }
        }
    }
}
```
