### ISSUE TITLE
[CSS] Default email domain input CSS is set twice

### ISSUE THREAD

**Issue by Jerom138** [KleeGroup/focus-components#215]
Replace 
```css
[data-focus="field"][data-mode="edit"][data-domain="DO_EMAIL"] input {
  width: 400px; }
[data-focus="field"][data-mode="edit"][data-domain="DO_EMAIL"] input {
  width: 100px; }
```
by
```css
[data-focus="field"][data-mode="edit"][data-domain="DO_EMAIL"] input {
  width: 400px; }
```
