### ISSUE TITLE
[Detail] Default css move the detail page below the menu

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#351]
The padding 10px cause the detail page to be below the nav menu.

Please replace :
```css
[data-focus="scrollspy"] nav {
    float: left;
    width: 200px;
    padding: 10px;
}
```
with 
```css
[data-focus="scrollspy"] nav {
    float: left;
    width: 200px;
}
```
