### ISSUE TITLE
[Fields] Various omissions in styling

### ISSUE THREAD

**Issue by JabX** [KleeGroup/focus-components#515]
Autocomplete misses a width property.
```css
[data-focus="autocomplete"] div {
    width: 100%;
}
```
solves it.

InputDate is too large and centered
```css
[data-focus="input-date"] > div {
    width: 100px;
    display: block;
}
```
solves it.

Before:
![problem](https://cloud.githubusercontent.com/assets/3266897/10362823/26528d1c-6db1-11e5-9b32-c5c41eb7b849.PNG)

After:
![solved](https://cloud.githubusercontent.com/assets/3266897/10362828/2cee32e8-6db1-11e5-8dfb-168addb34dfb.PNG)
