### ISSUE TITLE
Default position of error on field ?

### ISSUE THREAD

**Issue by Jerom138** [KleeGroup/focus-components#588]
With 
```css
 .mdl-textfield__error {
    position: absolute;
} 
```
, the error can be superpose with the next field.

Should not be 
```css
.mdl-textfield__error {
    position: relative;
}
```
