### ISSUE TITLE
[navigation Bar] - Highlight of item in navigation Bar

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#640]
### Context
I've got a navigation bar (classic)

### Actual behaviour
Buttons doesn't highlight when selected / when the corresponding page is active.

### Expected behaviour
Highlight of the active session.
Is it possible to create some stuff to higlight the buttons in the navigation bar according to the page rendered on screen ?

### Versions
Focus-core : 0.11.0
Focus-component: 0.7.3-3
Focus-File: 0.1.2

**Comment by pierr** [comment]
@Pandakls can you use the issue mode available here https://github.com/KleeGroup/focus-components/blob/develop/CONTRIBUTE.md 
Two options 
- There is  the application store, the menu component can listen to it 
- Do it with the `data-route` option in css (not the best)

**Comment by pierr** [comment]
@Pandakls propose a Pull Request?

**Comment by pierr** [comment]
@Pandakls Do you feel motivated for writing a PR?

**Comment by Bernardstanislas** [comment]
Here is how to do it with CSS
```CSS
[data-route='myRoute'] + div {
    // Here we are in the menu component, so do your selection as you wish
    // For example, select the nth child
    li:nth-of-type(2) {
        background-color: red;
    }
}
```
