### ISSUE TITLE
Checkbox: Validation, error, and Material styling

### ISSUE THREAD

**Issue by Hartorn** [KleeGroup/focus-components#923]
Currently, the Checkbox ('focus-components/components/input/checkbox') does not allow to have an error on it.
It could be useful, especially when creating account for user : you want to force them to accep the conditions of use.

I was expecting the following behaviour :

``` jsx
        const checkboxOptions = {
            hasLabel: true,
            FieldComponent: Checkbox,
            validator: [{
                type: 'function',
                value: (checked) => (checked ? true : false),
                options: { translationKey: 'error.utilisateur.cgu.accept'},
            }]
        };
 ....
    {this.fieldFor('cgu', checkboxOptions)}
```

But it is not working.

I tried to solve it, but encounter another problem, it seems the classes for material-design are not upgraded properly at the validation (linked to issue #908 ?).

![checkboxerror](https://cloud.githubusercontent.com/assets/4953724/12640912/da350816-c5ac-11e5-9ece-09678cc004a8.PNG)

Could you check why the classes `mdl-js-ripple-effect--ignore-events is-upgraded` are not added after validation ? Could the problem come from using fieldFor instead of the component directly ?

Here are the changes I made :
On the component class :
``` jsx
import React, {Component, PropTypes} from 'react';
import ReactDOM from 'react-dom';
import Translation from '../../../behaviours/translation';
import Material from '../../../behaviours/material';

const propTypes = {
    label: PropTypes.string,
    onChange: PropTypes.func.isRequired,
    value: PropTypes.bool.isRequired
};

const defaultProps = {
    value: false
};

const displayName = 'InputCheckBox';

@Translation
@Material('mdlHolder')
class InputCheckBox extends Component {
    getValue = () => {
        const domElement = ReactDOM.findDOMNode(this.refs.checkbox);
        return domElement.checked;
    };

    componentDidUpdate() {
        const {value} = this.props;
        const method = value ? 'add' : 'remove';
        const node = ReactDOM.findDOMNode(this.refs.mdlHolder);
        if (node) {
            node.classList[method]('is-checked');
        }
    }

    handleOnChange({target: {checked}}) {
        const {onChange} = this.props;
        onChange(checked);
    }

    render() {
        const {label, value, error} = this.props; /* Extracting the error props */
        return (
            <label className={`mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect`} data-focus='input-checkbox' ref='mdlHolder'>
                <input checked={value} className='mdl-checkbox__input' onChange={::this.handleOnChange} ref='checkbox' type='checkbox'/>
                {label && <span className='mdl-checkbox__label'>{this.i18n(label)}</span>}
                {error && <span className='mdl-checkbox__error'>{this.i18n(error)}</span>}{/* New line to handle error */}
            </label>
        );
    }
}

InputCheckBox.propTypes = propTypes;
InputCheckBox.defaultProps = defaultProps;
InputCheckBox.displayName = displayName;

export default InputCheckBox;
```

Some CSS to have it displayed properly : 
``` scss
// Gestion CSS de l'erreur sur les checkboxs
.mdl-checkbox.is-invalid {
  color: #de3226;
}

.mdl-checkbox__error {
    color: rgb(222, 50, 38);
    position: absolute;
    font-size: 12px;
    margin-top: 3px;
    visibility: hidden;
    display: block;
}

.mdl-checkbox.is-invalid .mdl-checkbox__error{
  visibility: visible;
}

.mdl-checkbox {
  padding-bottom: 20px;
  height:100%;
  margin:7px 0;
}
```
