### ISSUE TITLE
[Form] [TextArea] keep newlines

### ISSUE THREAD

**Issue by xuaveneg** [KleeGroup/focus-components#935]
Hi,

In an editable form, when a user enter a newline character in a textarea, this one is replaced by a space in consult mode.
Is it possible to keep the newlines entered by the user in consult mode ?

Thanks !

**Comment by durandx** [comment]
Use the following class for your div :

```css
.pre-wrap  {
    white-space: pre-wrap;       /* CSS 3 */
    white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
    white-space: -pre-wrap;      /* Opera 4-6 */
    white-space: -o-pre-wrap;    /* Opera 7 */
    word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
```
