### ISSUE TITLE
[Checkbox] Regression following the Focus release

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#994]
# Current behaviour
The tick in the checkboxes are not displayed. We got a 404 in the browser for tick-mask.svg

# Expected behaviour
 Please fix the focus-components with the following code : 
```css
.mdl-checkbox__tick-outline {
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  -webkit-mask: url("../img/tick-mask.svg?embed");
          mask: url("../img/tick-mask.svg?embed");
  background: transparent;
  -webkit-transition-duration: 0.28s;
          transition-duration: 0.28s;
  -webkit-transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
          transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  -webkit-transition-property: background;
  transition-property: background; }
  .mdl-checkbox.is-checked .mdl-checkbox__tick-outline {
    background: rgb(63,81,181) url("../img/tick.svg?embed"); }
  .mdl-checkbox.is-checked.is-disabled .mdl-checkbox__tick-outline {
    background: rgba(0,0,0, 0.26) url("../img/tick.svg?embed"); }
```

```css
@supports (-webkit-appearance: none) {
  .mdl-progress:not(.mdl-progress__indeterminate):not(.mdl-progress__indeterminate) > .auxbar {
    background-image: -webkit-linear-gradient(left, rgba(255,255,255, 0.7), rgba(255,255,255, 0.7)), -webkit-linear-gradient(left, rgb(63,81,181), rgb(63,81,181));
    background-image: linear-gradient(to right, rgba(255,255,255, 0.7), rgba(255,255,255, 0.7)), linear-gradient(to right, rgb(63,81,181), rgb(63,81,181));
    -webkit-mask: url("../img/buffer.svg?embed");
            mask: url("../img/buffer.svg?embed"); } }
```

Please note that this fix the 404 error when the svg are downloaded, but the resulting tick is now ugly.

Before the focus release:
![image](https://cloud.githubusercontent.com/assets/9220437/13285362/7c597be2-dafa-11e5-9676-f2d88d9c5c84.png)

After the focus release using the patch above :
![image](https://cloud.githubusercontent.com/assets/9220437/13285375/8e334118-dafa-11e5-87a4-443b90eb304b.png)

Please apply the patch and fix the bad display of the tick (maybe the mask is no longer positionned correctly)

## Versions

Focus-core: 0.12.4
Focus-components: 0.8.6
